{
    "openapi": "3.0.0",
    "info": {
      "title": "SpaceX Dashboard API",
      "description": "Sistema de visualiza√ß√£o de lan√ßamentos de foguetes pela SpaceX. @Challenge by Coodesh",
      "version": "1.0.0"
    },
    "paths": {
      "/": {
        "get": {
          "summary": "Mostra a mensagem do Challenge",
          "tags": ["CHALLENGE"],
          "responses": {
            "200": {
              "description": "Mensagem do Challenge",
              "content": {
                "application/json": {
                  "examples": {
                    "GetMessage": {
                      "value": {
                        "message": "Fullstack Challenge üèÖ - Space X API"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "/launches": {
        "get": {
          "summary": "Retorna os lan√ßamentos de foguetes da SpaceX",
          "tags": ["Launches"],
          "parameters": [
            {
              "name": "search",
              "in":"query",
              "required": false,
              "schema": {
                "type": "string"
              }
            },
            {
                "name": "limit",
                "in":"query",
                "required": false,
                "schema": {
                  "type": "number"
                }
              },
              {
                "name": "page",
                "in":"query",
                "required": false,
                "schema": {
                  "type": "number"
                }
              }
          ],
          "responses": {
            "200": {
              "description": "Retorna os lan√ßamentos de foguetes da SpaceX",
              "content": {
                "application/json": {
                  "examples": {
                    "Retorna todos os lan√ßamentos": {
                      "summary": "Retorna os lan√ßamentos de foguetes da SpaceX",
                      "value": [
                        {
                          "fairings": {
                            "reused": false,
                            "recovery_attempt": false,
                            "recovered": false,
                            "ships": []
                          },
                          "links": {
                            "patch": {
                              "small": "https://images2.imgbox.com/94/f2/NN6Ph45r_o.png",
                              "large": "https://images2.imgbox.com/5b/02/QcxHUb5V_o.png"
                            },
                            "reddit": {
                              "campaign": null,
                              "launch": null,
                              "media": null,
                              "recovery": null
                            },
                            "flickr": {
                              "small": [],
                              "original": []
                            },
                            "presskit": null,
                            "webcast": "https://www.youtube.com/watch?v=0a_00nJ_Y88",
                            "youtube_id": "0a_00nJ_Y88",
                            "article": "https://www.space.com/2196-spacex-inaugural-falcon-1-rocket-lost-launch.html",
                            "wikipedia": "https://en.wikipedia.org/wiki/DemoSat"
                          },
                          "static_fire_date_utc": "2006-03-17T00:00:00.000Z",
                          "static_fire_date_unix": 1142553600,
                          "net": false,
                          "window": 0,
                          "rocket": "5e9d0d95eda69955f709d1eb",
                          "success": false,
                          "failures": [
                            {
                              "time": 33,
                              "altitude": null,
                              "reason": "merlin engine failure"
                            }
                          ],
                          "details": "Engine failure at 33 seconds and loss of vehicle",
                          "crew": [],
                          "ships": [],
                          "capsules": [],
                          "payloads": [
                            "5eb0e4b5b6c3bb0006eeb1e1"
                          ],
                          "launchpad": "5e9e4502f5090995de566f86",
                          "flight_number": 1,
                          "name": "FalconSat",
                          "date_utc": "2006-03-24T22:30:00.000Z",
                          "date_unix": 1143239400,
                          "date_local": "2006-03-25T10:30:00+12:00",
                          "date_precision": "hour",
                          "upcoming": false,
                          "cores": [
                            {
                              "core": "5e9e289df35918033d3b2623",
                              "flight": 1,
                              "gridfins": false,
                              "legs": false,
                              "reused": false,
                              "landing_attempt": false,
                              "landing_success": null,
                              "landing_type": null,
                              "landpad": null
                            }
                          ],
                          "auto_update": true,
                          "tbd": false,
                          "launch_library_id": null,
                          "id": "5eb87cd9ffd86e000604b32a",
                          "rocket_name": "Falcon 1",
                          "year": "2006"
                        }]
                    },
                    "Retorna os lan√ßamentos com pagina√ß√£o e busca":{
                        "summary": "Retorna os lan√ßamentos com pagina√ß√£o e busca",
                        "value": [
                            {
                                "results": [
                                    {
                                        "fairings": {
                                            "reused": false,
                                            "recovery_attempt": false,
                                            "recovered": false,
                                            "ships": []
                                        },
                                        "links": {
                                            "patch": {
                                                "small": "https://images2.imgbox.com/cd/48/NVrODg2G_o.png",
                                                "large": "https://images2.imgbox.com/97/11/mjn87zBs_o.png"
                                            },
                                            "reddit": {
                                                "campaign": "https://www.reddit.com/r/spacex/comments/7hjp03/falcon_heavy_demo_launch_campaign_thread/",
                                                "launch": "https://www.reddit.com/r/spacex/comments/7vg63x/rspacex_falcon_heavy_test_flight_official_launch/",
                                                "media": "https://www.reddit.com/r/spacex/comments/7vimtm/rspacex_falcon_heavy_test_flight_media_thread/",
                                                "recovery": null
                                            },
                                            "flickr": {
                                                "small": [],
                                                "original": [
                                                    "https://farm5.staticflickr.com/4745/40110304192_b0165b7785_o.jpg",
                                                    "https://farm5.staticflickr.com/4676/40110297852_6173e5cae6_o.jpg",
                                                    "https://farm5.staticflickr.com/4615/40143096241_0324643b5e_o.jpg",
                                                    "https://farm5.staticflickr.com/4702/40110298232_4e9c412936_o.jpg",
                                                    "https://farm5.staticflickr.com/4610/39337245575_41d760caef_o.jpg",
                                                    "https://farm5.staticflickr.com/4654/25254688767_59603ff06c_o.jpg",
                                                    "https://farm5.staticflickr.com/4627/40126462801_d54b4f00be_o.jpg",
                                                    "https://farm5.staticflickr.com/4760/40126462231_cdf00ef431_o.jpg",
                                                    "https://farm5.staticflickr.com/4655/40202121122_5d29cfe2ac_o.jpg",
                                                    "https://farm5.staticflickr.com/4631/39337245145_5f5630a66a_o.jpg",
                                                    "https://farm5.staticflickr.com/4650/40126461851_14b93ec9d7_o.jpg",
                                                    "https://farm5.staticflickr.com/4711/40126461411_b1ed283d45_o.jpg",
                                                    "https://farm5.staticflickr.com/4696/40126460511_7b5cc64871_o.jpg",
                                                    "https://farm5.staticflickr.com/4589/38583831555_9ae89f5c10_o.jpg",
                                                    "https://farm5.staticflickr.com/4682/38583829815_e01509d1a7_o.jpg",
                                                    "https://farm5.staticflickr.com/4731/39225582801_80594d5d91_o.jpg",
                                                    "https://farm5.staticflickr.com/4641/39225582421_7aa0c65851_o.jpg",
                                                    "https://farm5.staticflickr.com/4643/27449864329_d2424bc280_o.jpg",
                                                    "https://farm5.staticflickr.com/4681/39225582171_137a4c75e7_o.jpg",
                                                    "https://farm5.staticflickr.com/4644/39225582351_ac6aba2533_o.jpg",
                                                    "https://farm5.staticflickr.com/4587/27449863849_709e135a98_o.jpg"
                                                ]
                                            },
                                            "presskit": "http://www.spacex.com/sites/spacex/files/falconheavypresskit_v1.pdf",
                                            "webcast": "https://www.youtube.com/watch?v=wbSwFU6tY1c",
                                            "youtube_id": "wbSwFU6tY1c",
                                            "article": "https://spaceflightnow.com/2018/02/07/spacex-debuts-worlds-most-powerful-rocket-sends-tesla-toward-the-asteroid-belt/",
                                            "wikipedia": "https://en.wikipedia.org/wiki/Elon_Musk%27s_Tesla_Roadster"
                                        },
                                        "static_fire_date_utc": "2018-01-24T17:30:00.000Z",
                                        "static_fire_date_unix": 1516815000,
                                        "net": false,
                                        "window": 9000,
                                        "rocket": "5e9d0d95eda69974db09d1ed",
                                        "success": true,
                                        "failures": [],
                                        "details": "The launch was a success, and the side boosters landed simultaneously at adjacent ground pads. Drone ship landing of the central core failed. Final burn to heliocentric mars-earth orbit was successful after the second stage and payload passed through the Van Allen belts.",
                                        "crew": [],
                                        "ships": [
                                            "5ea6ed2f080df4000697c90c",
                                            "5ea6ed2f080df4000697c90d",
                                            "5ea6ed30080df4000697c913"
                                        ],
                                        "capsules": [],
                                        "payloads": [
                                            "5eb0e4c6b6c3bb0006eeb21c"
                                        ],
                                        "launchpad": "5e9e4502f509094188566f88",
                                        "flight_number": 55,
                                        "name": "Falcon Heavy Test Flight",
                                        "date_utc": "2018-02-06T20:45:00.000Z",
                                        "date_unix": 1517949900,
                                        "date_local": "2018-02-06T15:45:00-05:00",
                                        "date_precision": "hour",
                                        "upcoming": false,
                                        "cores": [
                                            {
                                                "core": "5e9e28a5f359187f703b2653",
                                                "flight": 1,
                                                "gridfins": true,
                                                "legs": true,
                                                "reused": false,
                                                "landing_attempt": true,
                                                "landing_success": false,
                                                "landing_type": "ASDS",
                                                "landpad": "5e9e3032383ecb6bb234e7ca"
                                            },
                                            {
                                                "core": "5e9e28a2f359187f273b2642",
                                                "flight": 2,
                                                "gridfins": true,
                                                "legs": true,
                                                "reused": true,
                                                "landing_attempt": true,
                                                "landing_success": true,
                                                "landing_type": "RTLS",
                                                "landpad": "5e9e3032383ecb90a834e7c8"
                                            },
                                            {
                                                "core": "5e9e28a2f3591845c73b2640",
                                                "flight": 2,
                                                "gridfins": true,
                                                "legs": true,
                                                "reused": true,
                                                "landing_attempt": true,
                                                "landing_success": true,
                                                "landing_type": "RTLS",
                                                "landpad": "5e9e3032383ecb267a34e7c7"
                                            }
                                        ],
                                        "auto_update": true,
                                        "tbd": false,
                                        "launch_library_id": null,
                                        "id": "5eb87d13ffd86e000604b360",
                                        "rocket_name": "Falcon Heavy",
                                        "year": "2018"
                                    },
                                    {
                                        "fairings": {
                                            "reused": null,
                                            "recovery_attempt": null,
                                            "recovered": null,
                                            "ships": []
                                        },
                                        "links": {
                                            "patch": {
                                                "small": "https://images2.imgbox.com/73/7f/u7BKqv2C_o.png",
                                                "large": "https://images2.imgbox.com/66/b4/8KZsjbt4_o.png"
                                            },
                                            "reddit": {
                                                "campaign": null,
                                                "launch": null,
                                                "media": null,
                                                "recovery": null
                                            },
                                            "flickr": {
                                                "small": [],
                                                "original": []
                                            },
                                            "presskit": "http://forum.nasaspaceflight.com/index.php?action=dlattach;topic=21869.0;attach=230821",
                                            "webcast": "https://www.youtube.com/watch?v=nxSxgBKlYws",
                                            "youtube_id": "nxSxgBKlYws",
                                            "article": "http://www.spacex.com/news/2013/02/12/falcon-9-flight-1",
                                            "wikipedia": "https://en.wikipedia.org/wiki/Dragon_Spacecraft_Qualification_Unit"
                                        },
                                        "static_fire_date_utc": "2010-03-13T00:00:00.000Z",
                                        "static_fire_date_unix": 1268438400,
                                        "net": false,
                                        "window": 0,
                                        "rocket": "5e9d0d95eda69973a809d1ec",
                                        "success": true,
                                        "failures": [],
                                        "details": null,
                                        "crew": [],
                                        "ships": [],
                                        "capsules": [],
                                        "payloads": [
                                            "5eb0e4b7b6c3bb0006eeb1e7"
                                        ],
                                        "launchpad": "5e9e4501f509094ba4566f84",
                                        "flight_number": 6,
                                        "name": "Falcon 9 Test Flight",
                                        "date_utc": "2010-06-04T18:45:00.000Z",
                                        "date_unix": 1275677100,
                                        "date_local": "2010-06-04T14:45:00-04:00",
                                        "date_precision": "hour",
                                        "upcoming": false,
                                        "cores": [
                                            {
                                                "core": "5e9e289ef359185f2b3b2628",
                                                "flight": 1,
                                                "gridfins": false,
                                                "legs": false,
                                                "reused": false,
                                                "landing_attempt": false,
                                                "landing_success": null,
                                                "landing_type": null,
                                                "landpad": null
                                            }
                                        ],
                                        "auto_update": true,
                                        "tbd": false,
                                        "launch_library_id": null,
                                        "id": "5eb87cddffd86e000604b32f",
                                        "rocket_name": "Falcon 9",
                                        "year": "2010"
                                    }
                                ],
                                "totalDocs": 3,
                                "page": 1,
                                "totalPages": 2,
                                "hasNext": true,
                                "hasPrev": false
                            }
                        ]
                      }
                  }
                }
              }
            }
          }
        }
      },
      "/launches/stats": {
        "get": {
          "summary": "Retorna a contagem de lan√ßamentos de foguetes por ano e por resultado (sucesso ou falha)",
          "tags": ["Launches"],          
          "responses": {
            "200": {
              "description": "Sucesso",
              "content": {
                "application/json": {
                  "examples": {
                    "GetLaunchesStats": {
                      "summary": "Retorna a contagem de lan√ßamentos de foguetes por ano e por resultado (sucesso ou falha)",
                      "value": {
                        "Falcon 1": 5,
                        "Falcon 9": 178,
                        "Falcon Heavy": 3,
                        "success": 181,
                        "failure": 5,
                        "launch_by_year": [
                          {
                            "rocket": "Falcon 1",
                            "year": "2006",
                            "count": 1
                          },
                          {
                            "rocket": "Falcon 1",
                            "year": "2007",
                            "count": 1
                          },
                          {
                            "rocket": "Falcon 1",
                            "year": "2008",
                            "count": 2
                          },
                          {
                            "rocket": "Falcon 1",
                            "year": "2009",
                            "count": 1
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2010",
                            "count": 2
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2012",
                            "count": 2
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2013",
                            "count": 3
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2014",
                            "count": 6
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2015",
                            "count": 7
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2016",
                            "count": 9
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2017",
                            "count": 18
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2018",
                            "count": 20
                          },
                          {
                            "rocket": "Falcon Heavy",
                            "year": "2018",
                            "count": 1
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2019",
                            "count": 11
                          },
                          {
                            "rocket": "Falcon Heavy",
                            "year": "2019",
                            "count": 2
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2020",
                            "count": 26
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2021",
                            "count": 31
                          },
                          {
                            "rocket": "Falcon 9",
                            "year": "2022",
                            "count": 43
                          }
                        ]
                      }
                    }
                  }
                }
              }
            },
            "404": {
              "description": "√â retornado quando um produto n√£o √© encontrado",
              "content": {
                "application/json": {
                  "examples": {
                    "Error": {
                      "summary": "Error",
                      "value": {
                        "statusCode": 404,
                        "message": "product with id '101' not found",
                        "error": "Not Found"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "Launches": {
          "type": "object",
          "properties": {
            "flight_number": {
              "type": "Number",
              "required": true
            },
            "name": {
              "type": "String",
              "unique": true,
              "required": true
            },
            "date_utc": {
              "type": "String",
              "required": true
            },
            "date_unix": {
              "type": "Number",
              "required": true
            },
            "date_local": {
              "type": "String",
              "required": true
            },
            "date_precision": {
              "type": "String",
              "required": true,
              "enum": [
                "half",
                "quarter",
                "year",
                "month",
                "day",
                "hour"
              ]
            },
            "static_fire_date_utc": {
              "type": "String",
              "default": null
            },
            "static_fire_date_unix": {
              "type": "Number",
              "default": null
            },
            "tdb": {
              "type": "Boolean",
              "default": false
            },
            "net": {
              "type": "Boolean",
              "default": false
            },
            "window": {
              "type": "Number",
              "default": null
            },
            "rocket": {
              "type": "UUID",
              "default": null
            },
            "success": {
              "type": "Boolean",
              "default": null
            },
            "failures": [
              {
                "time": {
                  "type": "Number"
                },
                "altitude": {
                  "type": "Number"
                },
                "reason": {
                  "type": "String"
                }
              }
            ],
            "upcoming": {
              "type": "Boolean",
              "required": true
            },
            "details": {
              "type": "String",
              "default": null
            },
            "fairings": {
              "reused": {
                "type": "Boolean",
                "default": null
              },
              "recovery_attempt": {
                "type": "Boolean",
                "default": null
              },
              "recovered": {
                "type": "Boolean",
                "default": null
              },
              "ships": [
                "UUID"
              ]
            },
            "crew": [
              {
                "crew": {
                  "type": "UUID",
                  "default": null
                },
                "role": {
                  "type": "String",
                  "default": null
                }
              }
            ],
            "ships": [
              "UUID"
            ],
            "capsules": [
              "UUID"
            ],
            "payloads": [
              "UUID"
            ],
            "launchpad": {
              "type": "UUID",
              "default": null
            },
            "cores": [
              {
                "core": {
                  "type": "UUID",
                  "default": null
                },
                "flight": {
                  "type": "Number",
                  "default": null
                },
                "gridfins": {
                  "type": "Boolean",
                  "default": null
                },
                "legs": {
                  "type": "Boolean",
                  "default": null
                },
                "reused": {
                  "type": "Boolean",
                  "default": null
                },
                "landing_attempt": {
                  "type": "Boolean",
                  "default": null
                },
                "landing_success": {
                  "type": "Boolean",
                  "default": null
                },
                "landing_type": {
                  "type": "String",
                  "default": null
                },
                "landpad": {
                  "type": "UUID",
                  "default": null
                }
              }
            ],
            "links": {
              "patch": {
                "small": {
                  "type": "String",
                  "default": null
                },
                "large": {
                  "type": "String",
                  "default": null
                }
              },
              "reddit": {
                "campaign": {
                  "type": "String",
                  "default": null
                },
                "launch": {
                  "type": "String",
                  "default": null
                },
                "media": {
                  "type": "String",
                  "default": null
                },
                "recovery": {
                  "type": "String",
                  "default": null
                }
              },
              "flickr": {
                "small": [
                  "String"
                ],
                "original": [
                  "String"
                ]
              },
              "presskit": {
                "type": "String",
                "default": null
              },
              "webcast": {
                "type": "String",
                "default": null
              },
              "youtube_id": {
                "type": "String",
                "default": null
              },
              "article": {
                "type": "String",
                "default": null
              },
              "wikipedia": {
                "type": "String",
                "default": null
              }
            },
            "auto_update": {
              "type": "Boolean",
              "default": true
            },
            "id": {
                "type": "String",
                "default": null                
            }
          }
        }
      }
    }
  }